using System;
using System.Collections.Generic;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using UnityEngine;

namespace VeeItemInfo;

/// <summary>
/// The public preview: one HTML page listing every item and what the overlay shows for it.
///
/// Generated by the mod from the real <see cref="ItemDescriptionBuilder.Build"/>, so it can
/// never disagree with the overlay - and equally it is not a specification and cannot catch
/// a bug on its own. It is the accurate picture, and the baseline any specification is
/// written against. This replaced a Python generator that re-derived the display rules from
/// wiki numbers and drifted from the code within a week.
///
/// No artwork lives in the repository: every icon is hotlinked from peak.wiki.gg, whose file
/// names are the item's display name with underscores. Status icons are white silhouettes
/// there exactly as they are in the game, so a tinted sprite becomes a CSS mask filled with
/// the surrounding text colour - the same thing TMP's <c>tint=1</c> does.
/// </summary>
internal static class PreviewPage
{
    internal sealed class Row
    {
        internal Row(Item item, string? built, string? error)
        {
            Item = item;
            Built = built;
            Error = error;
        }

        internal Item Item { get; }

        /// <summary>The overlay's rich text, or null where Build threw.</summary>
        internal string? Built { get; }

        internal string? Error { get; }
    }

    private const string Thumb = "https://peak.wiki.gg/images/thumb/{0}.png/64px-{0}.png";
    private const string Wiki = "https://peak.wiki.gg/wiki/";

    /// <summary>
    /// Wiki file names for every sprite the overlay can emit. Statuses first - the wiki keeps
    /// them under Status_*, with two names that differ from the game's (Extra Stamina is
    /// "Bonus stamina" there, Shield is "Invincibility") - then the item icons the overlay
    /// borrows for the rope pair, the balloons and the generic item glyph.
    ///
    /// Whether a sprite is tinted is not decided here: the sprite tag carries tint=0 or 1,
    /// set by StatusIcons.ShouldTint from the texture, and the page follows the tag.
    /// </summary>
    private static readonly Dictionary<string, string> Files = new()
    {
        { "Hunger", "Status_Hunger" },
        { "ExtraStamina", "Status_Bonus_stamina" },
        { "Injury", "Status_Injury" },
        { "Poison", "Status_Poison" },
        { "Cold", "Status_Cold" },
        { "Hot", "Status_Heat" },
        { "Heat", "Status_Heat" },
        { "Drowsy", "Status_Drowsy" },
        { "Spores", "Status_Spores" },
        { "Thorns", "Status_Thorns" },
        { "Weight", "Status_Weight" },
        { "Curse", "Status_Curse" },
        { "Petrify", "Status_Petrify" },
        { "Shield", "Status_Invincibility" },
        { "Numb", "Status_Numb" },
        { "Web", "Status_Web" },
        { "Arrow", "Status_Arrow" },
        { "FlyTrap", "Status_FlyTrap" },
        { "Item", "Bing_Bong" },
        { "RopeCannon", "Rope_Cannon" },
        { "RopeCannonAnti", "Anti-Rope_Cannon" },
        { "RopeSpool", "Rope_Spool" },
        { "RopeSpoolAnti", "Anti-Rope_Spool" },
        { "Float", "Balloon" },
        { "FloatBunch", "Balloon_Bunch" },
    };

    /// <summary>
    /// The wiki has no campfire status icon - the mod scrapes the real one off the stamina
    /// bar at runtime - and a stovetop item icon standing in for it read as an item rather
    /// than as "fire". An emoji says it and costs no request.
    /// </summary>
    private const string CookEmoji = "🔥";

    /// <summary>
    /// The three things the overlay's rich text is made of: a colour open, a colour close,
    /// and a sprite. Everything between them is plain text.
    /// </summary>
    private static readonly Regex Tag = new(
        "<#([0-9A-Fa-f]{6})>|</color>|<sprite name=\"([^\"]+)\" tint=(\\d)>", RegexOptions.Compiled);

    internal static string Render(List<Row> rows)
    {
        rows.Sort((a, b) => string.Compare(DisplayName(a.Item), DisplayName(b.Item),
            StringComparison.OrdinalIgnoreCase));

        StringBuilder page = new();
        page.Append("<!doctype html><html lang=en><head><meta charset=utf-8>\n")
            .Append("<meta name=viewport content='width=device-width,initial-scale=1'>\n")
            .Append("<title>VeeItemInfo &ndash; Item Preview</title>\n")
            .Append("<style>").Append(Css).Append("</style></head><body>\n");

        page.Append("<header><h1>VeeItemInfo &ndash; Item Preview</h1>\n")
            .Append("<p class=sub>What the overlay shows for every item in the game. Generated by the mod ")
            .Append("itself from the same code that draws the overlay, so this page cannot disagree with it.</p>\n")
            .Append("<p class=meta>PEAK ").Append(Escape(Application.version))
            .Append(" &middot; VeeItemInfo ").Append(Escape(Plugin.Version))
            .Append(" &middot; ").Append(rows.Count).Append(" items &middot; generated ")
            .Append(DateTime.Now.ToString("yyyy-MM-dd")).Append("</p>\n")
            .Append("<p class=note>Numbers are on the settings the page was generated with: a full status bar is ")
            .Append(PluginConfig.StatusScale.Value).Append(", distances in ")
            .Append(PluginConfig.UnityMetres.Value ? "Unity units" : "PEAK metres")
            .Append(". Every item is shown uncooked. A Shroomberry's colours and stamina come from the run the page ")
            .Append("was generated in; other runs roll differently.</p>\n")
            .Append("<input id=q type=search placeholder='Filter items&hellip;' autocomplete=off>\n")
            .Append("</header>\n");

        page.Append("<table><colgroup><col class=c-icon><col class=c-name><col></colgroup>\n")
            .Append("<tr><th></th><th>Item</th><th>Overlay</th></tr>\n");

        foreach (Row row in rows)
        {
            string name = DisplayName(row.Item);
            string file = WikiFile(name);
            page.Append("<tr data-name=\"").Append(Escape(name.ToLowerInvariant())).Append(' ')
                .Append(Escape(row.Item.gameObject.name.ToLowerInvariant())).Append("\">")
                .Append("<td><img class=item src=\"").Append(string.Format(Thumb, file))
                .Append("\" alt=\"\" loading=lazy onerror=\"this.remove()\"></td>")
                .Append("<td><div class=name><a href=\"").Append(Wiki).Append(file)
                .Append("\" target=_blank rel=noopener>").Append(Escape(name)).Append("</a></div>")
                .Append("<div class=internal>").Append(Escape(row.Item.gameObject.name)).Append("</div></td>")
                .Append("<td>");

            if (row.Built != null)
            {
                page.Append("<div class=ov>").Append(ToHtml(row.Built)).Append("</div>");
            }
            else
            {
                page.Append("<div class=failed>Build threw: ").Append(Escape(row.Error ?? "")).Append("</div>");
            }

            page.Append("</td></tr>\n");
        }

        page.Append("</table>\n")
            .Append("<script>")
            .Append("const q=document.getElementById('q');q.addEventListener('input',()=>{const t=q.value.trim().toLowerCase();")
            .Append("for(const r of document.querySelectorAll('tr[data-name]'))r.hidden=t!==''&&!r.dataset.name.includes(t);});")
            .Append("</script>\n</body></html>\n");

        return page.ToString();
    }

    /// <summary>
    /// The overlay's TMP rich text as HTML. Colour tags become spans, sprites become wiki
    /// icons, newlines become breaks and everything else is escaped text.
    /// </summary>
    internal static string ToHtml(string richText)
    {
        StringBuilder html = new();
        int last = 0;
        foreach (Match match in Tag.Matches(richText))
        {
            AppendText(html, richText.Substring(last, match.Index - last));
            last = match.Index + match.Length;

            if (match.Groups[1].Success)
            {
                html.Append("<span style=\"color:#").Append(match.Groups[1].Value).Append("\">");
            }
            else if (match.Groups[2].Success)
            {
                html.Append(Icon(match.Groups[2].Value, match.Groups[3].Value == "1"));
            }
            else
            {
                html.Append("</span>");
            }
        }

        AppendText(html, richText.Substring(last));
        return html.ToString();
    }

    private static void AppendText(StringBuilder html, string text)
    {
        html.Append(Escape(text).Replace("\n", "<br>"));
    }

    /// <summary>
    /// One sprite. A tinted one is a mask over <c>currentColor</c>, so it takes the colour
    /// of the span it sits in exactly as the game's tint=1 sprite takes the text colour; an
    /// untinted one is the wiki's image as it is. A key with no wiki file is shown as its
    /// name, so a gap in the table above is visible rather than blank.
    /// </summary>
    private static string Icon(string name, bool tinted)
    {
        if (name == "Cook")
        {
            return "<span class=emoji title=Cook>" + CookEmoji + "</span>";
        }

        if (!Files.TryGetValue(name, out string? file))
        {
            return "<span class=fallback>" + Escape(name) + "</span>";
        }

        string url = string.Format(Thumb, file);
        if (!tinted)
        {
            return "<img class=si src=\"" + url + "\" alt=\"" + Escape(name) + "\" loading=lazy>";
        }

        return "<span class=\"si tint\" style=\"-webkit-mask-image:url(" + url + ");mask-image:url(" + url
            + ")\" title=\"" + Escape(name) + "\"></span>";
    }

    /// <summary>
    /// The name a player knows the item by, in the case the wiki files it under.
    ///
    /// GetName is the game's localisation and always has the right words, but in the HUD's
    /// upper case - "GRANOLA BAR" - and wiki file names are case-sensitive. UIData.itemName
    /// was tried first and is worse: it is the localisation key's source and is a key for
    /// some items ("AMULET_CLONE", "VOIDLAUNCHER") and lower case for others. So the
    /// localised name is title-cased, with the small words the wiki keeps lower - "Bugle of
    /// Friendship", "The Book of Bones" - left alone.
    /// </summary>
    private static string DisplayName(Item item)
    {
        string? name = null;
        try
        {
            name = item.GetName();
        }
        catch (Exception)
        {
            // Localisation not up; fall through to the raw name.
        }

        if (string.IsNullOrWhiteSpace(name))
        {
            name = item.UIData != null && !string.IsNullOrWhiteSpace(item.UIData.itemName)
                ? item.UIData.itemName
                : item.gameObject.name;
        }

        // Two amulets are spelled with a typographic apostrophe in the game; the wiki uses a
        // straight one everywhere, and TextInfo would capitalise the letter after a curly one.
        string cased = TitleCase(name!.Replace('’', '\''));
        return WikiAliases.TryGetValue(cased, out string? alias) ? alias : cased;
    }

    /// <summary>
    /// The few real items the wiki files under a different name from the game's own. Props,
    /// guidebook pages and unlocalised leftovers are not here - they have no page to find.
    /// </summary>
    private static readonly Dictionary<string, string> WikiAliases = new(StringComparer.Ordinal)
    {
        { "Coconut Half", "Half-Coconut" },
        { "Bird", "Cooked Bird" },
    };

    private static readonly HashSet<string> SmallWords = new(StringComparer.Ordinal)
    {
        "of", "the", "and", "a", "an", "in", "on", "to",
    };

    /// <summary>
    /// "SCOUT'S INITIATIVE" to "Scout's Initiative", "BUGLE OF FRIENDSHIP" to "Bugle of
    /// Friendship". TextInfo handles apostrophes and hyphens; the small-word rule is ours,
    /// and never applies to the first word.
    /// </summary>
    private static string TitleCase(string upper)
    {
        string[] words = System.Globalization.CultureInfo.InvariantCulture.TextInfo
            .ToTitleCase(upper.ToLowerInvariant()).Split(' ');
        for (int i = 1; i < words.Length; i++)
        {
            string lower = words[i].ToLowerInvariant();
            if (SmallWords.Contains(lower))
            {
                words[i] = lower;
            }
        }

        return string.Join(" ", words);
    }

    /// <summary>Display name to wiki file and page name: underscores for spaces, apostrophes escaped.</summary>
    private static string WikiFile(string displayName) =>
        displayName.Replace(' ', '_').Replace("'", "%27");

    private static string Escape(string text) => WebUtility.HtmlEncode(text);

    private const string Css = @"
:root{--bg:#14181d;--panel:#1b2027;--panel2:#20262e;--line:#2c343e;--ink:#dfe6ee;--dim:#8d9aa8;--accent:#BFEC1B;--overlay:#0d1014}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 'Segoe UI',system-ui,sans-serif}
a{color:var(--accent);text-decoration:none}
header{padding:30px 32px 18px;border-bottom:1px solid var(--line);background:var(--panel);position:sticky;top:0;z-index:2}
h1{margin:0 0 6px;font-size:26px}
.sub{color:var(--dim);max-width:90ch;margin:0 0 4px}
.meta{color:var(--dim);font-size:12.5px;margin:0 0 4px}
.note{color:var(--dim);font-size:12.5px;max-width:100ch;margin:0 0 12px}
#q{width:min(100%,32ch);background:var(--overlay);color:var(--ink);border:1px solid var(--line);border-radius:6px;padding:7px 10px;font-size:14px}
table{width:100%;border-collapse:collapse;table-layout:fixed;margin:0 0 80px}
th{text-align:left;font-size:11.5px;letter-spacing:.09em;text-transform:uppercase;color:var(--dim);font-weight:600;padding:9px 12px;border-bottom:1px solid var(--line)}
td{padding:11px 12px;border-bottom:1px solid var(--line);vertical-align:top;font-size:13.5px}
tr:hover td{background:var(--panel2)}
col.c-icon{width:72px}col.c-name{width:26%}
img.item{width:48px;height:48px}
.name{font-weight:600}
.internal{color:var(--dim);font-size:11.5px;margin-top:2px}
.ov{display:inline-block;min-width:22ch;background:var(--overlay);border:1px solid var(--line);border-radius:6px;padding:8px 11px;font-family:Consolas,ui-monospace,monospace;font-size:13px;line-height:1.7;letter-spacing:.02em;white-space:nowrap}
.failed{color:#ff8fa3;font-family:Consolas,ui-monospace,monospace;font-size:12.5px}
img.si{height:1.1em;width:auto;vertical-align:-.2em;margin:0 .05em}
.si.tint{display:inline-block;height:1.1em;width:1.1em;vertical-align:-.2em;margin:0 .05em;background-color:currentColor;-webkit-mask-size:contain;mask-size:contain;-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;-webkit-mask-position:center;mask-position:center}
.emoji{font-size:1.05em;line-height:1}
.fallback{color:#ff8fa3;font-weight:600;font-size:.85em;letter-spacing:.06em}
";
}
